// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.0
// source: caculator.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Caculator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caculator) Reset() {
	*x = Caculator{}
	mi := &file_caculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caculator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caculator) ProtoMessage() {}

func (x *Caculator) ProtoReflect() protoreflect.Message {
	mi := &file_caculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caculator.ProtoReflect.Descriptor instead.
func (*Caculator) Descriptor() ([]byte, []int) {
	return file_caculator_proto_rawDescGZIP(), []int{0}
}

func (x *Caculator) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CaculatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaculatorRequest) Reset() {
	*x = CaculatorRequest{}
	mi := &file_caculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaculatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaculatorRequest) ProtoMessage() {}

func (x *CaculatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_caculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaculatorRequest.ProtoReflect.Descriptor instead.
func (*CaculatorRequest) Descriptor() ([]byte, []int) {
	return file_caculator_proto_rawDescGZIP(), []int{1}
}

func (x *CaculatorRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CaculatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaculatorResponse) Reset() {
	*x = CaculatorResponse{}
	mi := &file_caculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaculatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaculatorResponse) ProtoMessage() {}

func (x *CaculatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_caculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaculatorResponse.ProtoReflect.Descriptor instead.
func (*CaculatorResponse) Descriptor() ([]byte, []int) {
	return file_caculator_proto_rawDescGZIP(), []int{2}
}

func (x *CaculatorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_caculator_proto protoreflect.FileDescriptor

var file_caculator_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x63, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x61, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2c, 0x0a, 0x10, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d,
	0x0a, 0x11, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x52, 0x0a,
	0x10, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3e, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x66, 0x75, 0x6e, 0x6e, 0x7a, 0x79,
	0x2d, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_caculator_proto_rawDescOnce sync.Once
	file_caculator_proto_rawDescData []byte
)

func file_caculator_proto_rawDescGZIP() []byte {
	file_caculator_proto_rawDescOnce.Do(func() {
		file_caculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_caculator_proto_rawDesc), len(file_caculator_proto_rawDesc)))
	})
	return file_caculator_proto_rawDescData
}

var file_caculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_caculator_proto_goTypes = []any{
	(*Caculator)(nil),         // 0: protos.Caculator
	(*CaculatorRequest)(nil),  // 1: protos.CaculatorRequest
	(*CaculatorResponse)(nil), // 2: protos.CaculatorResponse
}
var file_caculator_proto_depIdxs = []int32{
	1, // 0: protos.CaculatorService.Hello:input_type -> protos.CaculatorRequest
	2, // 1: protos.CaculatorService.Hello:output_type -> protos.CaculatorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_caculator_proto_init() }
func file_caculator_proto_init() {
	if File_caculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_caculator_proto_rawDesc), len(file_caculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caculator_proto_goTypes,
		DependencyIndexes: file_caculator_proto_depIdxs,
		MessageInfos:      file_caculator_proto_msgTypes,
	}.Build()
	File_caculator_proto = out.File
	file_caculator_proto_goTypes = nil
	file_caculator_proto_depIdxs = nil
}
